//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Colaboradores
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Colaboradores()
        {
            this.RegistrosDiarios = new HashSet<RegistrosDiarios>();
        }
    
        public string COD_Colaborador { get; set; }
        public string COD_Empresa { get; set; }
        public int ID_Area { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public string Nombres { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public System.DateTime FechaContratacion { get; set; }
        public System.DateTime FechaIngresoReingreso { get; set; }
        public System.DateTime FechaCese { get; set; }
        public string Direccion { get; set; }
        public byte[] Foto { get; set; }
        public string Cargo { get; set; }
        public bool Estado { get; set; }
    
        public virtual Areas Areas { get; set; }
        public virtual Empresas Empresas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RegistrosDiarios> RegistrosDiarios { get; set; }
    }
}
