//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IDCHECKDBEntities : DbContext
    {
        public IDCHECKDBEntities()
            : base("name=IDCHECKDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Areas> Areas { get; set; }
        public virtual DbSet<Calendarios> Calendarios { get; set; }
        public virtual DbSet<Colaboradores> Colaboradores { get; set; }
        public virtual DbSet<Empresas> Empresas { get; set; }
        public virtual DbSet<TiposDeDias> TiposDeDias { get; set; }
        public virtual DbSet<Ubigeos> Ubigeos { get; set; }
        public virtual DbSet<RegistrosDiarios> RegistrosDiarios { get; set; }
    }
}
