//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistrosDiarios
    {
        public int ID_RegistroDiario { get; set; }
        public string COD_Colaborador { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<System.DateTime> FechaYHoraIngreso { get; set; }
        public Nullable<System.DateTime> FechaYHoraSalida { get; set; }
    
        public virtual Colaboradores Colaboradores { get; set; }
    }
}
